const Router = require('koa-router');
const Login = require('./Auth/login');
const Register = require('./Auth/register');
const Auth = require('./Auth/auth');
const ChangePwd = require('./User/changePwd');
const User = require('./User/user');
const Vote = require('./Vote/vote');
const VoteDetail = require('./Vote/id');
const Group = require('./Group/group');
const GroupDetail = require('./Group/id');
let router = new Router();
router.use('/auth', Login.routes(), Login.allowedMethods());
router.use('/auth', Register.routes(), Register.allowedMethods());
router.use('/auth', Auth.routes(), Auth.allowedMethods());
router.use('/user', ChangePwd.routes(), ChangePwd.allowedMethods());
router.use('/user', User.routes(), User.allowedMethods());
router.use('/vote', Vote.routes(), Vote.allowedMethods());
router.use('/vote', VoteDetail.routes(), VoteDetail.allowedMethods());
router.use('/group', Group.routes(), Group.allowedMethods());
router.use('/group', GroupDetail.routes(), GroupDetail.allowedMethods());
module.exports = router;